### ISSUE TITLE
How can to configure the electricsheep client?

### ISSUE THREAD

**Issue by froggeric** [guysoft/ElectricSheepPi#4]
I cannot find out how to configure the client, as I would like to add my gold credentials and setup a few options? Is there a text file to edit?

The normal way would be to run electricsheep-preferences, but this is not possible through SSH, and I cannot exit the screensaver to the desktop. If you know how to do it, please add it the documentation.

**Comment by guysoft** [comment]
You should be able to edit a text file and do that.
I don't know how to test it because I have no gold credentials.

Thete is a text file I got mentioned here: https://github.com/scottdraves/electricsheep/issues/69 
perhaps its where it should go.
Would appreciate help here from @scottdraves who maintains the client. Its not my code.

**Comment by guysoft** [comment]
Closing due to no reply
